name: Code Quality - WPCS

on:
  pull_request:
    branches: "*"
  push:
    branches: "*"

jobs:
  lint:
    name: PHP Lint
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout
        uses: actions/checkout@v2

      # Setup PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      # Get composer cache directory
      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      # Cache composer dependencies
      - name: Cache Composer Dependencies
        uses: actions/cache@v2.1.6
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      # Install composer packages
      - name: Install Composer Packages
        run: |
          composer install --no-progress

      # Run the WPCS linting command
      - name: Run WPCS Lint
        run: composer run-script lint:wpcs
